### PR TITLE
Added enum, equals and hashcode support.

### PR DESCRIPTION
**Pull request by jbrick**
This also changes to using spaces instead of tabs.

I'll link to a diff of outputs using the old parcelgen vs the updated version when I get some time.

### CODE REVIEW

**Comment by jbrick** [comment]
```java
{
	"do_json": true,
	"package": "com.yelp.android.serializable",
	"class_name": "_EventRsvp",
	"props": {
		"String": [
			"testString"
		],
	    "int[]": [
		  "arraytest"
		],
	    "enum": [
		  {"testEnum" : ["state_one", "state_two"]},
		  {"testEnum2": ["state_one", "state_two"]}
		]
	}
}
```

```java
package com.yelp.android.serializable;

import android.os.Parcel;
import android.os.Parcelable;
import com.yelp.parcelgen.EqualsUtil;
import com.yelp.parcelgen.HashCodeUtil;
import com.yelp.parcelgen.JsonUtil;
import java.util.Arrays;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/** Automatically generated Parcelable implementation for _EventRsvp.
 *    DO NOT MODIFY THIS FILE MANUALLY! IT WILL BE OVERWRITTEN THE NEXT TIME
 *    _EventRsvp's PARCELABLE DESCRIPTION IS CHANGED.
 */
/* package */ abstract class _EventRsvp implements Parcelable {

    protected String mTestString;
    protected TestEnum mTestEnum;
    protected TestEnum2 mTestEnum2;
    protected int[] mArraytest;

    protected _EventRsvp(String testString, TestEnum testEnum, TestEnum2 testEnum2, int[] arraytest) {
        this();
        mTestString = testString;
        mTestEnum = testEnum;
        mTestEnum2 = testEnum2;
        mArraytest = arraytest;
    }

    protected _EventRsvp() {
        super();
    }

    @Override
    public boolean equals(Object object) {
        if ( this == object ) return true;

        if ( !(object instanceof _EventRsvp)) return false;

        _EventRsvp that = (_EventRsvp) object;

        return
            EqualsUtil.areEqual(this.mTestString, that.mTestString) &&
            EqualsUtil.areEqual(this.mTestEnum, that.mTestEnum) &&
            EqualsUtil.areEqual(this.mTestEnum2, that.mTestEnum2) &&
            Arrays.equals(this.mArraytest, that.mArraytest);
    }

    @Override
    public int hashCode() {
        int result = HashCodeUtil.SEED;
        result = HashCodeUtil.hash(result, mTestString);
        result = HashCodeUtil.hash(result, mTestEnum);
        result = HashCodeUtil.hash(result, mTestEnum2);
        result = HashCodeUtil.hash(result, mArraytest);
        return result;
    }

    public String getTestString() {
         return mTestString;
    }
    public TestEnum getTestEnum() {
         return mTestEnum;
    }
    public TestEnum2 getTestEnum2() {
         return mTestEnum2;
    }
    public int[] getArraytest() {
         return mArraytest;
    }


    public int describeContents() {
        return 0;
    }

    public void writeToParcel(Parcel parcel, int flags) {
        parcel.writeString(mTestString);
        parcel.writeSerializable(mTestEnum);
        parcel.writeSerializable(mTestEnum2);
        parcel.writeIntArray(mArraytest);
    }

    public void readFromParcel(Parcel source) {
        mTestString = source.readString();
        mTestEnum = (TestEnum)source.readSerializable();
        mTestEnum2 = (TestEnum2)source.readSerializable();
        mArraytest = source.createIntArray();

    }

    public void readFromJson(JSONObject json) throws JSONException {
        if (!json.isNull("test_string")) {
            mTestString = json.optString("test_string");
        }
        if (!json.isNull("test_enum")) {
            mTestEnum = TestEnum.valueOf(JsonUtil.toCamelCase(json.optString("test_enum")));
        }
        if (!json.isNull("test_enum2")) {
            mTestEnum2 = TestEnum2.valueOf(JsonUtil.toCamelCase(json.optString("test_enum2")));
        }
        if (!json.isNull("arraytest")) {
            JSONArray jsonArray = json.getJSONArray("arraytest");
            int arrayLen = jsonArray.length();
            mArraytest = new int[arrayLen];
            for (int i = 0; i < arrayLen; i++) {
                mArraytest[i] = jsonArray.getInt(i);
            }
        }
    }
}
```

```java
package com.yelp.android.serializable;

import android.os.Parcel;
import org.json.JSONException;
import org.json.JSONObject;
import org.json.JSONArray;
import com.yelp.parcelgen.JsonParser.DualCreator;


public class EventRsvp extends _EventRsvp {

    public static final DualCreator<EventRsvp> CREATOR = new DualCreator<EventRsvp>() {

        public EventRsvp[] newArray(int size) {
            return new EventRsvp[size];
        }

        public EventRsvp createFromParcel(Parcel source) {
            EventRsvp object = new EventRsvp();
            object.readFromParcel(source);
            return object;
        }

        @Override
        public EventRsvp parse(JSONObject obj) throws JSONException {
            EventRsvp newInstance = new EventRsvp();
            newInstance.readFromJson(obj);
            return newInstance;
        }
    };

}
```



```java
package com.yelp.android.serializable;

public enum TestEnum {
    StateOne("state_one"),
    StateTwo("state_two");

    public String apiString;

    private TestEnum(String apiString) {
        this.apiString = apiString;
    }
}
```

**Comment by tmelz** [comment]
thanks for the PR. overall the work looks good; i'm concerned about some subtle bugs coming up in the future. for example using a `short` or `byte` would be rare but isn't covered in `EqualsUtil`. in general, i think hashcode + equals are tricky to get right.

i don't know what the best reference impl is but apache common's [EqualsBuilder](http://grepcode.com/file/repo1.maven.org/maven2/commons-lang/commons-lang/2.6/org/apache/commons/lang/builder/EqualsBuilder.java#EqualsBuilder) and [HashCodeBuilder](http://grepcode.com/file/repo1.maven.org/maven2/commons-lang/commons-lang/2.1/org/apache/commons/lang/builder/HashCodeBuilder.java#HashCodeBuilder) are promising. pulling in apache commons would be non-ideal, but perhaps we could snag just these two classes.

open to discussing the different options!

**Comment by jbrick** [comment]
So short and byte in EqualsUtil are handled through implicit conversion. These util classes come from http://www.javapractices.com/topic/TopicAction.do?Id=17. However, I would agree that using a library implementation for something like this is a better idea in general. 

I'll take a look at the Apache stuff.

**Comment by tmelz** [comment]
if you decide to use any of the code from that site please review the legal situation and make sure the code is attributed.

**Comment by jbrick** [comment]
Updated to use Apache commons builders. New Equals and HashCode:

```Java
    @Override
    public boolean equals(Object object) {
        if (object == null) { return false; }
        if (object == this ) { return true; }
        if (object.getClass() != getClass()) { return false; }

        _AddressAttribute that = (_AddressAttribute) object;

        return new EqualsBuilder()
                .appendSuper(super.equals(object))
                .append(this.mExample, that.mExample)
                .append(this.mLabel, that.mLabel)
                .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder()
                .append(mExample)
                .append(mLabel)
                .toHashCode();
    }
```

**Comment by tmelz** [comment]
Thanks for the update, I'll take a look at this in the morning. What are the consequences of calling `EqualsBuilder#appendSuper(super.equals(object))`? Will this enforce that objects are only equal if they are the same reference? Is this preserved across parceling (I have no idea)?

**Comment by jbrick** [comment]
Your exactly right, it adds the result of super.equals() which in all these auto-generated objects case is just Object.equals(). This is not preserved across parcelling and is also just not the behaviour we want or we would just use the Object.equals() and wouldn't need this PR. 

I ran into this while testing and updated the PR to remove it, but forgot to update my comment.

**Comment by tmelz** [comment]
Looks great! Thanks for iterating on this!

**Pull request merged**
