### PR TITLE
fix UnboundLocalError: local variable 'targetFile' referenced before …

### PR DESCRIPTION
**Pull request by alanhamlett**
…assignment

### CODE REVIEW

**Comment by alanhamlett** [comment]
Any eta on when this will be merged?

**Comment by alanhamlett** [comment]
Any feedback on this PR?

**Comment by alanhamlett** [comment]
Any feedback on this PR?

**Comment by alanhamlett** [comment]
Any feedback on this PR?

**Comment by alanhamlett** [comment]
Any feedback on this PR?

**Comment by jbrick** [comment]
Hey! Sorry for the super late reply, this isn't a project we put a ton of active maintenance into. I can look at merging this, 

Can you resolve the merge conflicts, and add a little description about the bug, what causes the exception to occur?

**Comment by alanhamlett** [comment]
Sure, just fixed the merge conflicts. The bug is fixed with https://github.com/Yelp/parcelgen/pull/59/commits/a1907b6e9069e0074c48f66c8f82bd5b8e42cd4b. The cause of the bug was using `targetFile` without first defining it, which happened because `targetFile` is only defined when `if os.path.isdir(output)` evaluates to `True` but `targetFile` is always used regardless of that if condition.

**Pull request merged**
